(#7) : adiciona documento abstrac-factory
UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_03 pull request #27
Opened 2024-12-17 22:49 UTC by TalesRG

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [ ] Documentação
- [ ] Novo funcionalidade
- [ ] Correção de bug 
- [ ] Refatoração
- [ ] "Não sei dizer o que mudou, mas nada está igual" (Victor & Leo)

### Descrição
Por favor, faça um resumo do que mudou.

2024-12-18 00:25 UTC, klmurussi requested changes, later dismissed
Também atualizar a sidebar.

2024-12-18 00:25 UTC, klmurussi commented on docs/PadroesDeProjeto/criacionais/3.1.2.Abstract-Factory.md
> +## Introdução
Nenhuma referência linkada sobre o assunto.

2024-12-18 00:25 UTC, klmurussi commented on docs/PadroesDeProjeto/criacionais/3.1.2.Abstract-Factory.md
> +## Gravação da Reunião
Adicionar link da reunião se tiver, ou excluir essa parte.

2024-12-18 00:25 UTC, klmurussi commented on docs/PadroesDeProjeto/criacionais/3.1.2.Abstract-Factory.md
> +## Bibliografia
Só tem isso de referência?

2025-01-06 00:08 UTC, freitasc approved these changes

2025-01-06 00:10 UTC, merged