Prototype
UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_03 pull request #42
Opened 2024-12-18 00:27 UTC by analufernanndess

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [ ] Documentação
- [ ] Novo funcionalidade
- [ ] Correção de bug 
- [ ] Refatoração
- [ ] "Não sei dizer o que mudou, mas nada está igual" (Victor & Leo)

### Descrição
Por favor, faça um resumo do que mudou.

2024-12-18 00:34 UTC, klmurussi requested changes
Também atualizar a sidebar.

2024-12-18 00:34 UTC, klmurussi commented on docs/PadroesDeProjeto/Criacionais/3.1.4Prototype.md
> +```
Adicionar aqui análise dos resultados. Vi que foi criado apenas um exemplo base de protatype, se não for aplicado ao projeto, justificar o porquê. Acredito que seja, então também mudar o diagrama e os códigos **aplicando** ao projeto. Em qual(is) classes usar etc

2025-01-05 19:16 UTC, analufernanndess commented
ajustado

2025-01-06 03:28 UTC, klmurussi approved these changes

2025-01-06 03:29 UTC, merged